version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - sam build --use-container
  post_build:
    commands:
      - sam local invoke HelloWorldFunction
      - sam deploy --force-upload --no-confirm-changeset --resolve-s3